-- 0003_seed_words.sql
-- Seeds the 120-word bank so multiplayer and singleplayer draw from the
-- same source. Generated from src/data/words.ts by supabase/scripts/gen_seed.mjs
-- (do not hand-edit; regenerate if the word bank changes).
-- Idempotent: safe to re-run. Runs as the migration owner (postgres), which
-- bypasses RLS, so no client INSERT policy is needed on public.words.

insert into public.words (id, word, tier, definition, part_of_speech) values
  ('e1', 'garden', 'easy', 'A plot of land for growing plants', null),
  ('e2', 'pencil', 'easy', 'A tool used for writing or drawing', null),
  ('e3', 'yellow', 'easy', 'The color of a lemon', null),
  ('e4', 'castle', 'easy', 'A large fortified building', null),
  ('e5', 'bridge', 'easy', 'A structure that crosses a river or gap', null),
  ('e6', 'apple', 'easy', 'A round fruit that is often red or green', null),
  ('e7', 'basket', 'easy', 'A woven container used to carry or hold things', null),
  ('e8', 'candle', 'easy', 'A wax stick with a wick that burns to give light', null),
  ('e9', 'dolphin', 'easy', 'A smart sea animal that swims in groups and breathes air', null),
  ('e10', 'elephant', 'easy', 'A very large gray animal with a long trunk', null),
  ('e11', 'feather', 'easy', 'A light, soft part that covers a bird''s body', null),
  ('e12', 'giraffe', 'easy', 'A tall African animal with a very long neck', null),
  ('e13', 'hammer', 'easy', 'A tool used to pound nails into wood', null),
  ('e14', 'island', 'easy', 'A piece of land surrounded on all sides by water', null),
  ('e15', 'jacket', 'easy', 'A short coat worn over other clothing', null),
  ('e16', 'kitchen', 'easy', 'The room in a house where meals are cooked', null),
  ('e17', 'ladder', 'easy', 'A set of rungs used to climb up or down', null),
  ('e18', 'magnet', 'easy', 'An object that pulls certain metals toward it', null),
  ('e19', 'notebook', 'easy', 'A book of blank pages used for writing notes', null),
  ('e20', 'ocean', 'easy', 'A huge body of salt water covering much of the earth', null),
  ('e21', 'pillow', 'easy', 'A soft cushion used to rest your head on', null),
  ('e22', 'question', 'easy', 'A sentence asked in order to get information', null),
  ('e23', 'rainbow', 'easy', 'An arc of colors that appears in the sky after rain', null),
  ('e24', 'sandwich', 'easy', 'Food made by placing filling between two slices of bread', null),
  ('e25', 'teacher', 'easy', 'A person whose job is to help students learn', null),
  ('e26', 'umbrella', 'easy', 'A folding device used to stay dry in the rain', null),
  ('e27', 'village', 'easy', 'A small group of houses in the countryside', null),
  ('e28', 'window', 'easy', 'An opening in a wall that lets in light and air', null),
  ('e29', 'zebra', 'easy', 'An African animal known for its black and white stripes', null),
  ('e30', 'anchor', 'easy', 'A heavy object dropped from a boat to keep it in place', null),
  ('m1', 'rhythm', 'medium', 'A strong, regular repeated pattern of sound', null),
  ('m2', 'narrate', 'medium', 'To give a spoken account of something', null),
  ('m3', 'occasion', 'medium', 'A particular time or event', null),
  ('m4', 'vacuum', 'medium', 'A space entirely devoid of matter', null),
  ('m5', 'privilege', 'medium', 'A special right granted to a person or group', null),
  ('m6', 'absence', 'medium', 'The state of being away from a place where you''re expected', null),
  ('m7', 'achieve', 'medium', 'To succeed in finishing something through effort', null),
  ('m8', 'benefit', 'medium', 'An advantage or helpful result gained from something', null),
  ('m9', 'category', 'medium', 'A group of things that share common features', null),
  ('m10', 'colleague', 'medium', 'A person you work with, especially in a profession', null),
  ('m11', 'definite', 'medium', 'Clearly stated and not likely to change', null),
  ('m12', 'embarrass', 'medium', 'To make someone feel awkward or self-conscious', null),
  ('m13', 'exaggerate', 'medium', 'To describe something as larger or more extreme than it really is', null),
  ('m14', 'existence', 'medium', 'The state or fact of being real or alive', null),
  ('m15', 'fascinate', 'medium', 'To hold someone''s attention completely because it''s so interesting', null),
  ('m16', 'foreign', 'medium', 'Coming from or located in a country other than your own', null),
  ('m17', 'government', 'medium', 'The group of people who officially run a country or region', null),
  ('m18', 'harass', 'medium', 'To repeatedly bother or trouble someone', null),
  ('m19', 'humorous', 'medium', 'Causing laughter or amusement', null),
  ('m20', 'immediate', 'medium', 'Happening right away, without any delay', null),
  ('m21', 'jewelry', 'medium', 'Ornamental items like rings and necklaces worn on the body', null),
  ('m22', 'knowledge', 'medium', 'Information and understanding gained through learning or experience', null),
  ('m23', 'license', 'medium', 'An official document that gives permission to do something', null),
  ('m24', 'maintenance', 'medium', 'The work needed to keep something in good condition', null),
  ('m25', 'necessary', 'medium', 'Required in order for something to happen or be true', null),
  ('m26', 'occurrence', 'medium', 'Something that happens or takes place', null),
  ('m27', 'parallel', 'medium', 'Running side by side and always the same distance apart', null),
  ('m28', 'personnel', 'medium', 'The people who work for a particular organization', null),
  ('m29', 'questionnaire', 'medium', 'A written set of questions used to gather information from people', null),
  ('m30', 'recommend', 'medium', 'To suggest that something is good or suitable', null),
  ('h1', 'conscience', 'hard', 'An inner sense of right and wrong', null),
  ('h2', 'bureaucracy', 'hard', 'A system of government with many departments', null),
  ('h3', 'silhouette', 'hard', 'The dark shape of something against a light background', null),
  ('h4', 'millennium', 'hard', 'A period of one thousand years', null),
  ('h5', 'reconnaissance', 'hard', 'Military observation of enemy territory', null),
  ('h6', 'acquiesce', 'hard', 'To accept something without objecting, even reluctantly', null),
  ('h7', 'camaraderie', 'hard', 'A feeling of trust and friendship among a group of people', null),
  ('h8', 'circumference', 'hard', 'The distance measured around the outside edge of a circle', null),
  ('h9', 'connoisseur', 'hard', 'A person with expert knowledge and taste in a particular field', null),
  ('h10', 'deteriorate', 'hard', 'To become gradually worse in condition or quality', null),
  ('h11', 'entrepreneur', 'hard', 'A person who starts and runs their own business, taking on financial risk', null),
  ('h12', 'exacerbate', 'hard', 'To make an already difficult situation even worse', null),
  ('h13', 'extraordinary', 'hard', 'Far beyond what is usual or ordinary', null),
  ('h14', 'gregarious', 'hard', 'Fond of the company of others; very sociable', null),
  ('h15', 'hierarchy', 'hard', 'A system that ranks people or things in order of importance', null),
  ('h16', 'hypothesis', 'hard', 'An idea proposed as a starting point for further investigation', null),
  ('h17', 'indigenous', 'hard', 'Originating naturally in a particular place rather than arriving from elsewhere', null),
  ('h18', 'juxtaposition', 'hard', 'The placement of two contrasting things close together for effect', null),
  ('h19', 'kaleidoscope', 'hard', 'A tube of mirrors and colored glass that creates shifting patterns', null),
  ('h20', 'leisure', 'hard', 'Free time not taken up by work or obligations', null),
  ('h21', 'malevolent', 'hard', 'Having or showing a wish to cause harm to others', null),
  ('h22', 'nemesis', 'hard', 'A long-standing rival who seems impossible to overcome', null),
  ('h23', 'obsequious', 'hard', 'Overly eager to please or obey someone, often insincerely', null),
  ('h24', 'paradigm', 'hard', 'A typical example or pattern that serves as a model', null),
  ('h25', 'quintessential', 'hard', 'Representing the most perfect or typical example of something', null),
  ('h26', 'renaissance', 'hard', 'A period of renewed growth and creativity in a field or culture', null),
  ('h27', 'sovereignty', 'hard', 'The full authority a state has to govern itself', null),
  ('h28', 'tumultuous', 'hard', 'Marked by loud confusion, disorder, or violent change', null),
  ('h29', 'ubiquitous', 'hard', 'Seeming to appear everywhere at the same time', null),
  ('h30', 'vernacular', 'hard', 'The everyday language spoken by ordinary people in a region', null),
  ('x1', 'bromocriptine', 'expert', 'A drug used to treat certain hormonal disorders', null),
  ('x2', 'pharmaceutical', 'expert', 'Relating to the preparation of medicinal drugs', null),
  ('x3', 'onomatopoeia', 'expert', 'A word that phonetically imitates a sound', null),
  ('x4', 'idiosyncrasy', 'expert', 'A distinctive habit or peculiarity', null),
  ('x5', 'chiaroscuro', 'expert', 'The treatment of light and shade in art', null),
  ('x6', 'antediluvian', 'expert', 'Extremely old-fashioned, as if from before a great flood', null),
  ('x7', 'bildungsroman', 'expert', 'A novel that follows its main character''s growth from youth to maturity', null),
  ('x8', 'chrysanthemum', 'expert', 'A flowering plant known for its many-petaled autumn blooms', null),
  ('x9', 'doppelganger', 'expert', 'A person who looks strikingly like someone else, as if a double', null),
  ('x10', 'ebullient', 'expert', 'Overflowing with excitement and high spirits', null),
  ('x11', 'fatuous', 'expert', 'Silly and pointless in a way that shows poor judgment', null),
  ('x12', 'gesticulate', 'expert', 'To wave your arms and hands while speaking to emphasize a point', null),
  ('x13', 'hegemony', 'expert', 'Dominant influence or control held by one group over others', null),
  ('x14', 'ignominious', 'expert', 'Causing public shame or disgrace', null),
  ('x15', 'kowtow', 'expert', 'To act in an overly submissive way toward someone in authority', null),
  ('x16', 'labyrinthine', 'expert', 'Extremely complicated and full of confusing twists, like a maze', null),
  ('x17', 'mellifluous', 'expert', 'Sweet and smooth sounding, especially describing a voice', null),
  ('x18', 'nefarious', 'expert', 'Wicked or criminal in a deliberate, calculated way', null),
  ('x19', 'obfuscate', 'expert', 'To make something unclear or hard to understand on purpose', null),
  ('x20', 'pachyderm', 'expert', 'A large thick-skinned mammal such as an elephant or rhinoceros', null),
  ('x21', 'quixotic', 'expert', 'Idealistic to an unrealistic or impractical degree', null),
  ('x22', 'rhinoceros', 'expert', 'A large thick-skinned mammal with one or two horns on its snout', null),
  ('x23', 'sycophant', 'expert', 'A person who flatters others to gain personal advantage', null),
  ('x24', 'taciturn', 'expert', 'Habitually saying very little', null),
  ('x25', 'unctuous', 'expert', 'Excessively and insincerely flattering or smooth in manner', null),
  ('x26', 'vicissitude', 'expert', 'An unexpected change in circumstances, often for the worse', null),
  ('x27', 'wunderkind', 'expert', 'A person who achieves great success at a young age', null),
  ('x28', 'xenophobia', 'expert', 'An intense fear or dislike of people from other countries', null),
  ('x29', 'yttrium', 'expert', 'A silvery metallic chemical element used in certain alloys and lasers', null),
  ('x30', 'zeitgeist', 'expert', 'The defining mood or spirit of a particular period in history', null)
on conflict (id) do update set
  word = excluded.word,
  tier = excluded.tier,
  definition = excluded.definition,
  part_of_speech = excluded.part_of_speech;
